Creating route /alumniSitestatistics
computacao-ufcg/alumni-backend pull request #50
Opened 2021-02-22 20:59 UTC by natalia-sa

Creating new route /alumniSiteStatistics that provides data to alumni site.
New classes:
- AlumniSiteStatistics 
- AlumniSiteStatisticsResponse

2021-02-23 14:52 UTC, paulojuniore approved these changes

2021-02-23 15:29 UTC, fubica requested changes

2021-02-23 15:29 UTC, fubica commented on src/main/java/br/edu/ufcg/computacao/alumni/api/http/request/AlumniSiteStatistics.java
> +            @ApiParam(value = ApiDocumentation.Token.AUTHENTICATION_TOKEN)
Além do nome, deve receber também o "level". Veja em outras rotas como isso é feito.

2021-02-24 08:15 UTC, fubica approved these changes

2021-02-24 08:15 UTC, merged